FORMAT: 1A
HOST: https://api.test.paysafe.com/bankaccountvalidator/

# Paysafe Bank Account Validation API

Polls is a simple API allowing consumers to view polls and vote in them.

# Release Notes

| Version   | Date          | Details |
|---        |---            |---      |
| 1.0       | April 2019    | <ul><li>Document Release</li></ul> |

<a name="apikey" title="Authentication"></a>
# Authentication

In order for you to use the Paysafe REST API, Paysafe must first set you up on their system and provide you with an API key. Your API key looks something like this:

  * Key Username – MerchantXYZ
  * Key Password – B-tst1-0-51ed39e4-312d02345d3f123120881dff9bb4020a89e8ac44cdfdcecd702151182fdc952272661d290ab2e5849e31bb03deede7e

Note this is not the same as your Merchant Back Office username and password.
The case-sensitive API key is sent using HTTP Basic Authentication. To use HTTP Basic Authentication, you must send the API key credentials using the Authorization header with every request. The Authorization header is constructed as follows:

  1. The Key Username and Key Password are combined into a string separated by a colon, e.g.,“Key Username:Key Password”.
  2. The resulting string literal is then encoded using Base64.
  3. The authorization method and a space (i.e., “Basic”) are then put before the encoded string.

For example, using the Key Username and Password examples above, the header is formed as follows:

``Authorization: Basic
TWVyY2hhbnRYWVo6Qi10c3QxLTAtNTFlZDM5ZTQtMzEyZDAyMzQ1ZDNmMTIzMTIwODgxZGZmOWJiNDAyMGE4OWU4YWM0NGNkZmRjZWNkNzAyMTUxMTgyZmRjOTU yMjcyNjYxZDI5MGFiMmU1ODQ5ZTMxYmIwM2RlZWRlN2U=``

For additional details, please refer to [http://en.wikipedia.org/wiki/Basic_access_authentication](http://en.wikipedia.org/wiki/Basic_access_authentication).

  **Note:** Your Production API key will be different from your Test API key. Contact your account manager for details. You must keep your API keys safe and ensure that it is used appropriately for your needs.

# URLs 

##  Test URL
In order to test your integration with Paysafe, use the following Test URL:

`https://api.test.paysafe.com`

For example:

`https://api.test.paysafe.com/bankaccountvalidator/v1/accounts/{account_id}/verifications`

## Production URL
In order to process live requests with Paysafe, use the following Production URL:

`https://api.paysafe.com`

For example:

`https://api.paysafe.com/bankaccountvalidator/v1/accounts/{account_id}/verifications`


<a name="globalinvalidcharacters" title="Global Invalid Characters"></a>
# Global Invalid Characters

You must not include any of the characters in the following table as values in any of your request parameters. If you do, your request will result in an error.

|    Character    |    HEX    |    Description                     |
|-----------------|-----------|------------------------------------|
| "               | 22        | Double quotes (or speech marks)    |
| ;               | 3B        | Semicolon                          |
| ^               | 5E        | Caret, circumflex                  |
| *               | 2A        | Asterisk                           |
| <               | 3C        | Less than (or open angled bracket) |
| /               | 2F        | Slash or divide                    |
| [               | 5B        | Opening bracket                    |
| ]               | 5D        | Closing bracket                    |
| \               | 5C        | Backslash                          |

# API

The Bank Account Validation API allows merchants to verify the ownership of their customers' bank accounts by having the customer provide banking credentials online.

The following request types are supported:

  * [Verifications](#verificationrequest)
  * [Customer Redirections](#redirectionrequest)
  * [Verification Lookups](#getverification)
 
  
**API Endpoint** 

`https://api.paysafe.com/bankaccountvalidator/v1`

**Resource Patterns**

|Endpoint URL                                       |Description                            |Action |
|---                                                |---                                    |---    |
|/accounts/account_id/verifications                 |Verify a Customer's Bank Account       |POST   |
|/redirect?session_id                               |Redirect a Customer to Validation UI   |GET    |
|/accounts/account_id/verifications/verification_id |Get Bank Account Details               |GET    |


# Complex JSON Objects

<a name="achbankaccountobject" title="ACH Bank Account Object"></a>
## ach
|Element            |Type                       |Description    |
|---                |---                        |---       |
|nickName           |string<br/>`length<=50`    |This is an alias defined by the customer for the bank account (e.g., "First Bank account").|
|accountNumber      |string<br/>`length=4-17`   |This is the bank account number.|
|accountHolderName  |string<br/>`length<=22`    |This is the name of the customer or company that owns the bank account.|
|routingNumber      |string<br/>`length=9`      |For USD accounts, this is the 9-digit routing number of the customer’s bank.|
|accountType        |enum                       |This is the bank account type. Possible values are:<ul><li>CHECKING</li><li>LOAN</li><li>SAVINGS</li></ul>|
|lastDigits         |string<br/>`length=2`      |This is the last two digits of the bank account number.|
|paymentToken       |string<br/>`length<=50`    |This is a token generated by Paysafe that represents the bank account and is returned in the response to the bank account creation request. It can be used in the place of bank account information in Direct Debit transactions.|

```apib
            {
                "nickName": "John's RBC Business Bank Account",
                "accountNumber": "511201",
                "routingNumber": "123456789",
                "accountHolderName": "XYZ Business",
                "accountType": "CHECKING"
            }
```

<a name="eftbankaccountobject" title="EFT Bank Account Object"></a>
## eft
|Element            |Type                       |Description                        |
|---                |---                        |---       |
|nickName           |string<br/>`length<=50`    |This is an alias defined by the customer for the bank account (e.g., "CIBC Account").|
|accountNumber      |string<br/>`length=4-12`   |This is the bank account number.|
|accountHolderName  |string<br/>`length<=30`    |This is the name of the customer or company that owns the bank account.|
|transitNumber      |string<br/>`length=5`      |This is the 5-digit transit number of the customer's bank branch.|
|institutionId      |string<br/>`length=3`      |This is the 3-digit institution ID of the customer’s bank branch.|
|accountType        |enum                       |This is the bank account type. Possible values are:<ul><li>CHECKING</li><li>LOAN</li><li>SAVINGS</li></ul>|
|lastDigits         |string<br/>`length=2`      |This is the last two digits of the bank account number.|
|paymentToken       |string<br/>`length<=50`    |This is a token generated by Paysafe that represents the bank account and is returned in the response to the bank account creation request. It can be used in the place of bank account information in Direct Debit transactions.|

```apib
            {
                "nickName" : "Sally's Bank of Montreal Account",
                "accountHolderName": "Sally",
                "accountNumber" : "511201",
                "transitNumber" : "25039",
                "institutionId" : "001",
                "billingAddressId": "60022f38-fd17-4731-909c-923930d0d5d4",
            }
```

<a name="profileobject" title="Profile Object"></a>
## profile
|Element            |Type                               |Description    |
|---                |---                                |---            |
|firstName          |string <br/>`length<=80`           |This is the customer’s first name. |
|middleName         |string <br/>`length<=80`           |This is the customer’s middle name. |
|lastName           |string <br/>`length<=80`           |This is the customer’s last name. |
|locale             |enum                               |This indicates the language of the user interface for the customer. <br/>Possible values are:<ul><li>en_CA - English</li><li>fr_CA - French</li></ul>|

<a name="returnlinksobject" title="returnLinks Object"></a>
## returnLinks

|Element    |Type           |Description|
|---        |---            |---|
|rel        |enum           |This is the link type that allows different endpoints to be targeted depending on the end state of the transaction. Possible values are:<ul><li>default - The default return URL that will be used if specific status return URL is not defined.</li><li>on_completed - Will be returned to this URL if the payment is completed.</li><li>on_failed - Will be returned to this URL if the payment fails.</li></ul>|
|href       |string         |This is the URI of the resource.|

```apib
{
    "returnLinks": [{
            "rel": "default",
            "href": "https://mysite.com"
        }
    ]
}
```

<a name="verificationsobject" title="Verifications Object"></a>
## Verifications
|Element            |Type                               |Description    |
|---                |---                                |---            |
|profile            |[profile](#profileobject)          |This is the some profile information about the customer.|
|bankscheme         |enum                               |This is the bank scheme for which the merchant wants to validate the account.<br/>Possible values are:<ul><li>[ACH](#achbankaccountobject)</li><li>[EFT](#eftbankaccountobject)</li></ul>|
|merchantRefNum     |string <br/>`length<=255`          |This is the merchant reference number created by the merchant and submitted as part of the request.|
|accountTypes       |enum                               |This is the list of bank account types that will be presented. <br/>Possible values are:<ul><li>SAVING</li><li>CHEQUING</li>/ul>|
|currencyCodes      |array                              |This is the currency of the bank accounts that will be presented.<br>Possible values are:<ul><li>CAD</li><li>USD</li></ul>|
|returnLinks        |[returnLinks](#returnlinksobject)         |These are links to which to redirect the customer, where applicable. |

+ `returnLinks` (object, required) - This is the URL to which to redirect the customer. You can customize the return URL based on the transaction status. The 'default' value is mandatory.
    + `rel` (enum) - This is the link type, allowing different endpoints to be targeted depending on the end state of the transaction. The link relation describes how this link relates to the previous call. 
        + default (string, required) - The default return URL that will be used if specific status return URL is not defined.
        + on_completed (string) - Will be returned to this URL if the bank account validation request is completed.
        + on_failed (string) - Will be returned to this URL if the bank account validation request fails.
    + `href` - The actual URL to which the customer will be redirected.
+ `bankScheme`:`EFT` (enum, required) - This is the bank scheme for which the merchant wants to validate the account. 
    + Members
        + ACH
        + EFT
+ `id`: `25f6dadf-176a-415f-95c9-6ff39ff697ba` (string) - This is the ID returned in the response. This ID can be used for future associated requests, e,g., to look up the bank account verification details. 
    _Read Only_, _length<=36_
+ `sessionId`:`MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz` (string) - This is the encoded id that is mapped to verification id. It will be used as a reference in other API calls.
    _Read Only, max<=255_
+ `status`:`INITIATED` (enum) - This shows the status of the bank account verification request.
    _Read Only_
    + Members
        + SUCCESS - The customer has validated their bank account successfully.
        + FAILED - The bank account validation has failed.
        + INITIATED - The merchant has initiated the bank account verification request.
        + INCOMPLETE -  The bank account validation could not be completed successfully, e.g., due to user inactivity or session timeout.
+ `statusMessage`:`message` (string) - This message will be returned if the *status* is FAILED or INCOMPLETE status.
    _Read Only, length<=255_
+ Include Links Verification
+ Include Bank Scheme



# Verify That the Service Is Accessible [GET /v1/monitor]
<a name="verifyservice" title="Verify Service"></a>

This call returns a status of READY if the API is available.

+ Response 200 (application/json)

  + Body
    
            {
                "status" : "READY"
            }

# Verifications [/verifications]
<a name="verifications" title="Verifications"></a>

## Create a Verification [POST /v1/accounts/{account_id}/verifications]
<a name="verificationrequest" title="Verification Request"></a>

Click on **Create a Verification** above to see how to send a bank account verification request to Paysafe.

+ Parameters

    + account_id:123456789 (string, required) - This is the merchant account number.

+ Attributes
    + Include Verification Request

+ Request Send a Bank Account Verification Request (application/json)

    + Headers

            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY

    + Body

            {
                "merchantRefNum": "1323563",
                "profile": {
                    "firstName": "Praveen",
                    "middleName": "Kumar",
                    "lastName": "Jain",
                    "locale": "en_US"
                },
                "accountTypes": [
                    "SAVING",
                    "CHEQUING"
                ],
                "currencyCodes": [
                    "CAD",
                    "USD"
                ],
                "returnLinks": [{
                    "rel": "default",
                    "href": "https://mysite.com/return"
                }],
                "bankscheme": "EFT"
            }

+ Response 201 (application/json)

    + Body

            {
                "merchantRefNum": "1323563",
                "profile": {
                    "firstName": "Praveen",
                    "middleName": "Kumar",
                    "lastName": "Jain",
                    "locale": "en_US"
                },
                "accountTypes": [
                    "SAVING",
                    "CHEQUING"
                ],
                "currencyCodes": [
                    "CAD",
                    "USD"
                ],
                "returnLinks": [{
                    "rel": "default",
                    "href": "https://mysite.com/return"
                }],
                "bankscheme": "ACH",
                "id": "6a275b7c-6f11-4ed1-ae77-21071724574a",
                "sessionId": "MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz",
                "status": "INITIATED",
                "links": [{
                    "rel": "redirect_bank_validation",
                    "href": "https://api.paysafe.com/bankaccountvalidator/v1/redirect?sessionId=MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz"
                }]
            }

## Redirect the Customer [GET /v1/redirect?{session_id}]
<a name="redirectionrequest" title="Customer Redirection Request"></a>

Click on **Redirect the Customer** above to see how to redirect a customer so they can validate their bank account details.

>**Note:** Because this is a redirect request, there is no synchronous response available.


+ Parameters

    + session_id:`MmM2OGNiNWMtMWNmYS0xMWU5LWFiMTQtZDY2M2JkODczZDkz` (string, required) - This is the *sessionId* returned in the response to the bank account verification request.

+ Request Initiate a Customer Redirect Request

    + Headers

            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY

+ Response 201 (application/json)

    + Body



## Get Verification [GET /v1/accounts/{account_id}/verifications/{verification_id}]
<a name="getverification" title="Look Up a Verification"></a>

Click on **Get Verification** above to see how to look up a Verification request using the ID returned in the response to the original request. The response will display to you the customer's bank account details.

+ Parameters

    + account_id:123456789 (string, required) - This is the merchant account number.
    + verification_id:`6a275b7c-6f11-4ed1-ae77-21071724574a` (string, required) - This is the ID returned in the response to the bank account verification request.

+ Request Look Up a Verification (application/json)

    + Headers

            Authorization: Basic YOUR-BASE64-ENCODED-API-KEY

+ Response 200 (application/json)

    + Body

            {
                "merchantRefNum": "1323563",
                "accountTypes": [
                    "SAVING",
                    "CHEQUING"
                ],
                "currencyCodes": [
                    "CAD",
                    "USD"
                ],
                "returnLinks": [{
                    "rel": "default",
                    "href": "https://mysite.com/return"
                }],
                "links": [{
                    "rel": "redirect_bank_validation",
                    "href": "https://api.paysafe.com/bankaccountvalidator/v1/verifications/<verificationId>/redirect"
                }],
                "id": "6a275b7c-6f11-4ed1-ae77-21071724574a",
                "sessionId": "MmM2OGNiNWMtMWNmYS0xMWU5LWFiMTQtZDY2M2JkODczZDkz",
                "status": "SUCCESS",
                "eft": {
                    "accountHolderName": "John Carta",
                    "institutionId": "001",
                    "transitNumber": "25039",
                    "lastDigits": "01",
                    "accountType": "SAVING",
                    "paymentToken": "uteurtue"
                },
                "profile": {
                    "firstName": "John",
                    "middleName": "",
                    "lastName": "Carta",
                    "locale": "en_US"
                }
            }

# Data Structures

## `Bank Scheme`
+ One of

    + ach (object) - These are ACH bank account details. **Note:** This is returned only in the [Get Verification Response](getverification).
    _Read Only_

        + Properties
            + `nickName`:`Jane account` (string) - This is an alias defined by the customer for the bank account (e.g., "First Bank account").
                _length<=50_
            + `accountNumber`:`123456789` (string) - This is the bank account number.
                _length=4-12_
            + `accountHolderName`:`Jane Smith` (string) - This is the account holder's name.
                _length<=30_
            + `routingNumber`:`123456789` (string) - This is the 9-digit routing number of the customer’s bank account.
                _length=9_
            + `accountType`:`SAVING` (enum) - This is the type of the bank account.
                - SAVINGS
                - CHEQUING
            + `lastDigits`:`en_CA` (string) - This is the last two digits of the bank account number.
                _length=2_
            + `paymentToken`:`8Y9u7WR3E32EB09J` (string) - This is the token associated with the bank account.
                _length<=50_

    + eft (object) - These are EFT bank account details. **Note:** This is returned only in the [Get Verification Response](getverification).
    _Read Only_

        + Properties
            + `nickName`:`Jane account` (string) - This is an alias defined by the customer for the bank account (e.g., "First Bank account").
                _length<=50_
            + `accountNumber`:`123456789` (string) - This is the bank account number.
                _length=4-12_
            + `accountHolderName`:`Jane Smith` (string) - This is the account holder's name.
                _length<=30_
            + `institutionId`:`123` (string) - This is the 3-digit institution ID of the customer’s bank branch.
                _length=3_
            + `transitNumber`:`Smith` (string) - This is the 5-digit transit number of the customer's bank branch.
                _length=5_
            + `accountType`:`SAVING` (enum) - This is the type of the bank account.
                - SAVINGS
                - CHEQUING
            + `lastDigits`:`en_CA` (string) - This is the last two digits of the bank account number.
                _length=2_
            + `paymentToken`:`8Y9u7WR3E32EB09J` (string) - This is the token associated with the bank account.
                _length<=50_

## `Link Verification`
+ rel:`redirect_bank_validation` (string) -  This is the link to the endpoint at the end of the transaction.
+ href: `https://api.paysafe.com/bankaccountvalidator/v1/redirect?sessionId=MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz`

## `Links Verification`
+ links (array[Link Verification]) - This is an array of links related to the resource.  

    Typically you will have reference to any parent resources, and a reference to the child resource (if applicable).
    You may also see links for any call to action flows.
    
    _Read Only_

## `Profile`
+ profile (object, required) - This is some profile information about the customer.  

    + Properties
        + `firstName`:`Jane` (string, required) - This is the customer's first name.
            _length<=80_
        + `middleName`:`Ellen` (string) - This is the customer's middle name.
            _length<=80_
        + `lastName`:`Smith` (string, required) - This is the customer's last name.
            _length<=80_
        + `locale`:`en_CA` (enum) - This indicates the language of the user interface.
            + Members
                + en_CA
                + fr_CA

## Return Links Lookup
+ `returnLinks` (object) - This is the URL to which to redirect the customer. You can customize the return URL based on the transaction status.
    _Read Only_

    + Properties
        + `rel` (enum) - This is the link type, allowing different endpoints to be targeted depending on the end state of the transaction. The link relation describes how this link relates to the previous call. 
            + default (string, required) - The default return URL that will be used if specific status return URL is not defined.
            + on_completed (string) - Will be returned to this URL if the bank account validation request is completed.
            + on_failed (string) - Will be returned to this URL if the bank account validation request fails.
        + `href` - The actual URL to which the customer will be redirected.

## `Verification Request`
+ `merchantRefNum`: `P1234` (string, required) - This is the merchant reference number created by the merchant and submitted as part of the request.
    _length<=255_
+ Include Profile
+ `accountTypes`:`[SAVING, CHEQUING]` (array) - This is the list of bank account types that will be presented. Possible values are: SAVING, CHEQUING
+ `currencyCodes`:`[CAD, USD]` (array) - This is the currency of the bank accounts that will be presented. Possible values are: CAD, USD
+ `returnLinks` (object, required) - This is the URL to which to redirect the customer. You can customize the return URL based on the transaction status. The 'default' value is mandatory.
    + `rel` (enum) - This is the link type, allowing different endpoints to be targeted depending on the end state of the transaction. The link relation describes how this link relates to the previous call. 
        + default (string, required) - The default return URL that will be used if specific status return URL is not defined.
        + on_completed (string) - Will be returned to this URL if the bank account validation request is completed.
        + on_failed (string) - Will be returned to this URL if the bank account validation request fails.
    + `href` - The actual URL to which the customer will be redirected.
+ `bankScheme`:`EFT` (enum, required) - This is the bank scheme for which the merchant wants to validate the account. 
    + Members
        + ACH
        + EFT
+ `id`: `25f6dadf-176a-415f-95c9-6ff39ff697ba` (string) - This is the ID returned in the response. This ID can be used for future associated requests, e,g., to look up the bank account verification details. 
    _Read Only_, _length<=36_
+ `sessionId`:`MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz` (string) - This is the encoded id that is mapped to verification id. It will be used as a reference in other API calls.
    _Read Only, max<=255_
+ `status`:`INITIATED` (enum) - This shows the status of the bank account verification request.
    _Read Only_
    + Members
        + SUCCESS - The customer has validated their bank account successfully.
        + FAILED - The bank account validation has failed.
        + INITIATED - The merchant has initiated the bank account verification request.
        + INCOMPLETE -  The bank account validation could not be completed successfully, e.g., due to user inactivity or session timeout.
+ `statusMessage`:`message` (string) - This message will be returned if the *status* is FAILED or INCOMPLETE status.
    _Read Only, length<=255_
+ Include Links Verification
+ Include Bank Scheme

## `Verification Lookup Request`
+ `merchantRefNum`: `P1234` (string) - This is the merchant reference number created by the merchant and submitted as part of the request.
    _Read Only, length<=255_
+ `accountTypes`:`[SAVING, CHEQUING]` (array) - This is the list of bank account types that will be presented. Possible values are: SAVING, CHEQUING
    _Read Only_
+ `currencyCodes`:`[CAD, USD]` (array) - This is the currency of the bank accounts that will be presented. Possible values are: CAD, USD
    _Read Only_
+ Include Return Links Lookup
+ Include Links Verification
+ `id`: `25f6dadf-176a-415f-95c9-6ff39ff697ba` (string) - This is the ID returned in the response. This ID can be used for future associated requests, e,g., to look up the bank account verification details. 
    _Read Only_, _length<=36_
+ `sessionId`:`MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz` (string) - This is the encoded id that is mapped to verification id. It will be used as a reference in other API calls.
    _Read Only, max<=255_
+ `status`:`SUCCESS` (enum) - This shows the status of the bank account verification request.
    _Read Only_
    + Members
        + SUCCESS - The customer has validated their bank account successfully.
        + FAILED - The bank account validation has failed.
        + INITIATED - The merchant has initiated the bank account verification request.
        + INCOMPLETE -  The bank account validation could not be completed successfully, e.g., due to user inactivity or session timeout.
+ `statusMessage`:`message` (string) - This message will be returned if the *status* is FAILED or INCOMPLETE status.
    _Read Only, length<=255_
+ Include Bank Scheme
+ Include Profile